### ISSUE TITLE
Memory Leak caused by not removing Glib TimeoutHandlers from dictionary 

### ISSUE THREAD

**Issue by midmohan** [GLibSharp/GtkSharp#42]
The FinalizerInfo class generated by OpaqueGen.cs doesnt remove the TimeoutHandler Ids added to the static dictionary private static IDictionary<uint, SourceProxy> source_handlers in Source.cs .
This would lead to the memory growing continuously with each source_handler added. Could see it filling up GBs in matter of few hours when used with Gstreamer pipelines and objects created with Gstreamer-Sharp bindings for C#

Raising a PR also. Can somebody point out if there is any workaround for this.

**Comment by midmohan** [comment]
![Gsttimeout](https://user-images.githubusercontent.com/27757402/74667014-751efd00-519a-11ea-9974-7ba07abf02d3.JPG)

**Comment by sdroege** [comment]
This is fixed now in https://github.com/GLibSharp/GtkSharp/pull/45
